#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Install our gems needed for yeomen
if [ ! -d $OPENSHIFT_DATA_DIR/gems ]; then
	echo "Making Gems dir"
	mkdir $OPENSHIFT_DATA_DIR/gems
fi

export GEM_HOME=$OPENSHIFT_DATA_DIR/gems
if [ `gem list compass -i` == 'false' ]; then
	echo "Install Gems"
	gem install compass 
fi

if [ ! -x $OPENSHIFT_DATA_DIR/bin/optipng ]; then
	# Install optipng it's in our git repo
	cd $OPENSHIFT_TMP_DIR
	tar -xzf $OPENSHIFT_REPO_DIR/binary/optipng-0.7.4.tgz
	cd "$OPENSHIFT_TMP_DIR"optipng-0.7.4
	echo "Configuring optipng"
	./configure \
	      --prefix=$OPENSHIFT_DATA_DIR
	echo "Configured optipng"
	make -j
	echo "Build optipng"
	make install
	echo "Installed optipng"
fi

# Check for phantomjs
export PATH=$OPENSHIFT_DATA_DIR/phantomjs-1.8.1-linux-x86_64/bin:$PATH

command -v phantomjs >/dev/null 2>&1 || {
	echo "Installing phantomjs"
	cd $OPENSHIFT_TMP_DIR
	curl -s http://phantomjs.googlecode.com/files/phantomjs-1.8.1-linux-x86_64.tar.bz2 > phanomjs-1.8.1.tar.bz2
	cd $OPENSHIFT_DATA_DIR/
	tar -xjf $OPENSHIFT_TMP_DIR/phantomjs-1.8.1.tar.bz2
	echo "phantom js installed"

}

#put all the things on the PATH
export PATH=$OPENSHIFT_DATA_DIR/bin:$OPENSHIFT_DATA_DIR/gems/bin:$OPENSHIFT_DATA_DIR/phantomjs-1.8.1-linux-x86_64/bin/:$PATH
export GEM_HOME=$OPENSHIFT_DATA_DIR/gems

export NODE_VERSION="0.8.18"
 
# This script builds and installs node.js into the $OPENSHIFT_DATA_DIR directory
# from source code. The node.js source tarball will be downloaded, compiled, and
# installed automatically only if a node binary does not exist in '../data/bin'
# or if an existing binary does not match the specified version above.
 
# NOTE: This can take while to compile on an openshift gear (@25min), so be
# patient. This wait can be mitigated by compiling binaries elsewhere, and
# copying them to the $OPENSHIFT_DATA_DIR directory. This script will only
# attempt to compile sources after testing the binary version.
 
export NODE_NAME="node-v$NODE_VERSION"
echo "build: Checking for $NODE_NAME binary \$OPENSHIFT_DATA_DIR/bin/node ..."
if [ -x $OPENSHIFT_DATA_DIR/bin/node ] && \
   [ "`$OPENSHIFT_DATA_DIR/bin/node -v`" = "v$NODE_VERSION" ]; then
  echo "build: $NODE_NAME is installed."
  exit 0
fi
 
echo "build: $NODE_NAME binary was not found, or is incorrect version."
export NODE_TARBALL="$NODE_NAME.tar.gz"
export NODE_TARBALL_PATH="$OPENSHIFT_TMP_DIR"$NODE_TARBALL
export NODE_TARBALL_SHA1=`curl -s \
    http://nodejs.org/dist/v$NODE_VERSION/SHASUMS.txt | \
    grep "$NODE_TARBALL" | awk '{ print $1 }'`
 
echo "build: Checking for source code \$OPENSHIFT_TMP_DIR/$NODE_TARBALL ..."
if [ ! -f $NODE_TARBALL_PATH ] || \
   [ "`sha1sum $NODE_TARBALL_PATH | grep \"$NODE_TARBALL_SHA1\" | \
       awk '{ print $1 }'`" != "$NODE_TARBALL_SHA1" ]; then
  echo "build: Downloading source code ..."
  curl -so $NODE_TARBALL_PATH \
      http://nodejs.org/dist/v$NODE_VERSION/$NODE_TARBALL
  echo "build: Downloaded source code."
else
  echo "build: Found source code $NODE_TARBALL_PATH"
fi
 
echo "build: Verifying $NODE_NAME source code ..."
if [ `sha1sum $NODE_TARBALL_PATH | grep "$NODE_TARBALL_SHA1" | \
    awk '{ print $1 }'` != "$NODE_TARBALL_SHA1" ]; then
  echo "build: ERROR: SHA1 Checksum verification failed! Exiting build process."
  exit 1
else
  echo "build: $NODE_NAME source code checksum verified."
fi
 
echo "build: Extracting $NODE_NAME source files ..."
tar zxCf $OPENSHIFT_TMP_DIR $NODE_TARBALL_PATH
cd "$OPENSHIFT_TMP_DIR"$NODE_NAME
echo "build: Extracted $NODE_NAME source files."
 
if [ ! -f ./config.mk ]; then
  echo "build: Configuring $NODE_NAME ... "
  ./configure \
      --prefix=$OPENSHIFT_DATA_DIR \
      --without-waf \
      --shared-openssl \
      --shared-openssl-includes=/usr/local/include/ \
      --shared-openssl-libpath=/usr/local/lib/ \
      --shared-zlib \
      --shared-zlib-includes=/usr/local/include/ \
      --shared-zlib-libpath=/usr/local/lib/
  echo "build: Configured $NODE_NAME"
fi
 
echo "build: Building $NODE_NAME (Be patient) ... "
make -j
echo "build: Built $NODE_NAME"
 
echo "build: Installing $NODE_NAME ... "
make install
echo "build: $NODE_NAME is installed."

#Finally install yeoman
command -v yeoman >/dev/null 2>&1 || {
	echo "Installing yeoman"
	npm install -g yeoman
	echo "Yeoman installed"
}

